### ISSUE TITLE
Missing translation Error after input 4 number of password

### ISSUE THREAD

**Issue by EasonWang01** [CoinSpace/CoinSpace#10]
<img width="1186" alt="2017-11-19 2 17 09" src="https://user-images.githubusercontent.com/11001914/32989176-75de3ece-cd4c-11e7-8f4c-77c3d6d94dde.png">

**Comment by nikashitsa** [comment]
Sorry for inconvenience. Problem was on server side. Now all should work.

**Comment by iwonapiasecka** [comment]
19.11.2017 6:52 PM "nikashitsa" <notifications@github.com> napisał(a):

**Comment by iwonapiasecka** [comment]
21.11.2017 5:33 AM iwcia263811@gmail.com napisał(a):

19.11.2017 6:52 PM "nikashitsa" <notifications@github.com> napisał(a):

Closed #10 <https://github.com/CoinSpace/CoinSpace/issues/10>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CoinSpace/CoinSpace/issues/10#event-1348855334>, or mute
the thread
